source "https://rubygems.org"

gem "rack"
gem "yui-compressor"
gem "uglifier"
gem "sass"
gem "compass"
gem "roy-lang", git: "https://github.com/tmcgilchrist/ruby-roy.git"
gem "rake-pipeline", git: "https://github.com/livingsocial/rake-pipeline.git"
gem "rake-pipeline-web-filters", git: "git://github.com/ethul/rake-pipeline-web-filters.git", branch: "feature-roy-filter"
